port: 8080
log-level: info
use-custom-id: true

ynab:
  budget_id: a10ef71e-85c2-42d7-a008-262cf085911a
  token: $YNAB_ACCESS_TOKEN
  accounts:
    - name: "Itau Conta Corrente"
      id: "a06f5d5f-8272-4e5f-9e8e-c4ac09809d5a"
    - name: "Itau Cartão"
      id: "c0b73d4c-fcb4-4cda-a3f5-cf1e29bd498b"