name: Helm

on:
  push:
    tags: ['v*']

jobs:
  release-charts:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Charts
        run: |
          helm package helm/ynabu
          version=$(helm show chart helm/ynabu | grep '^version:' | cut -d' ' -f2)
          helm push ynabu-${version}.tgz oci://ghcr.io/yurifrl/charts