name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  prepare-release:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Get Version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Update Versions
        run: |
          version=${{ steps.version.outputs.version }}
          yq -i '.appVersion = strenv(version)' helm/ynabu/Chart.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add helm/ynabu/Chart.yaml
          git commit -m "chore: update versions for release v${{ steps.version.outputs.version }}"
          git push

      - name: Create Tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          generate_release_notes: true